---
stages:
  - update
  - lint
  - test
  - lsif
  - publish
variables:
  PIP_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/pip'
cache:
  key: '${CI_JOB_NAME}'
  paths:
    - .cache/pip
    - .pnpm-store
    - .venv
include:
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/common.gitlab-ci.yml
  - remote: https://gitlab.com/megabyte-labs/gitlab-ci/-/raw/master/publish/semantic-release.gitlab-ci.yml
