---
stages:
  - update
  - lint
  - test
  - lsif
  - publish
variables:
  PIP_CACHE_DIR: '${CI_PROJECT_DIR}/.cache/pip'
cache:
  key: '${CI_JOB_NAME}'
  paths:
    - .cache/pip
    - .pnpm-store
    - .venv
include:
  - remote: https://gitlab.com/megabyte-labs/common/shared/-/raw/master/.gitlab-ci.yml
